name: Test & Deploy
on: push
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v0.18.17
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - run: npm install
      - uses: Homebrew/actions/setup-homebrew@29b2973f18e5aca5443f4b3d87f68eda7a27b22b
      - run: brew install ldid
      - run: |
          cp node_modules/@npcz/magic/dist/magic.mgc assets/magic.mgc
          npx --yes pkg --no-bytecode --public-packages "*" --public package.json
          for cmd in '' runner publish pr; do build/cml-linux-x64 $cmd --version; done
          cp build/cml-linux{-x64,}
          cp build/cml-macos{-x64,}
      - run:
          find build -type f | xargs gh release upload v0.18.17
        env:
          GITHUB_TOKEN: ${{ github.token }}
  images:
    needs: packages
    secrets: inherit
    uses: ./.github/workflows/images.yml
    with:
      release: true
